# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areahood', '0003_auto_20181019_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='product',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
