# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areahood', '0006_auto_20181019_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='neighbourhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='areahood.Neighbourhood'),
        ),
    ]
